name: 'SARIF-to-GitHub-Issues-Action-Parsing-SARIF'
description: 'Parsing SARIF files for SARIF-to-GitHub-Issues-Action'
author: '@RealWorldVulnerabilityEdu (realworldvulnerabilityedu.github.io)'

# Inputs to the action.
inputs:
  toolkit-path:
    description: 'Directory where the SARIF-to-GitHub-Issues toolkit is'
    required: true
    default: '_s2ghi_toolkit_'
  sarif-data-path:
    description: 'Directory where the SARIF files are'
    default: '_s2ghi_/sarif_data' # "${{steps.codeql_analysis.outputs.sarif-output}}"
  qhelp-root:
    description: 'Root URL for QHELP'
    required: true
    default: 'http://www.sci.brooklyn.cuny.edu/~chen/uploads/research/qhelp'
  issue-data-path:
    description: 'Directory where the output issue data will be'
    required: true
    default: '_s2ghi_/issue_data'

# Outputs of the action.
outputs:
  status:
    description: 'Your run status here'

runs:
  using: 'composite'
  steps:
    - name: Set up Python for post analysis script
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Generate GH issue content
      shell: bash
      run: |
        if "$HOME/${{inputs.toolkit-path}}/parsesarif.sh" \
          "${{github.repository}}" \
          "${{github.sha}}" \
          "${{inputs.sarif-data-path}}" \
          "${{inputs.toolkit-path}}" \
          "${{inputs.qhelp-root}}" \
          "${{inputs.issue-data-path}}"; then
          ls -l "${{inputs.issue-data-path}}"
          echo "::set-output name=status::success"
        else:
          echo "::set-output name=status::failure"
        fi
