name: 'SARIF-to-GitHub-Issues-Action-Init'
description: 'Intialization for SARIF-to-GitHub-Issues-Action'
author: '@RealWorldVulnerabilityEdu (realworldvulnerabilityedu.github.io)'

# Inputs to the action.
inputs:
  toolkit-version:
    description: 'SARIF-to-GitHub issues tookkit version'
    required: true
    default: 'v0.001'
  toolkit-path:
    description: 'SARIF-to-GitHub issues tookkit directory'
    required: false
    default: '_s2ghi_toolkit_'
  toolkit-url:
    description: 'SARIF-to-GitHub issues tookkit URL'
    required: false
    default: 'http://www.sci.brooklyn.cuny.edu/~chen/uploads/research/ghissues/'
  sarif-data-path:
    description: 'Directory where the SARIF files are'
    required: true
    default: '_s2ghi_/sarif_data'
  qhelp-root:
    description: 'Root URL for QHELP'
    required: false
    default: 'http://www.sci.brooklyn.cuny.edu/~chen/uploads/research/qhelp'
  issue-data-path:
    description: 'Directory where the output issue data will be'
    required: false
    default: '_s2ghi_/issue_data'
  repository:
    description: 'Repository name (ower/reponame)'
    required: true
  sha:
    description: 'SHA of the commit the SAST tool was run on'
    required: true

# Outputs of the action.
outputs:
  toolkit-path:
    description: 'Directory where the SARIF-to-GitHub-Issues toolkit is'
  file-list:
    description: 'List of files in the toolkit directory'
  time:
    description: 'The time the action was executed'

runs:
  using: docker
  image: Dockerfile
  entrypoint: /run_toolkit.sh
  env:
    INPUTS_TOOLKIT_VERSION: ${{ inputs.toolkit-version }}
    INPUTS_TOOLKIT_PATH: ${{ inputs.toolkit-path }}
    INPUTS_TOOLKIT_URL: ${{ inputs.toolkit-url }}
    INPUTS_TOOLKIT_TOOLS: ${{ inputs.toolkit-tools }}
    INPUTS_REPOSITORY: ${{ inputs.repository }}
    INPUTS_SHA: ${{ inputs.sha }}
    INPUTS_SARIF_DATA_PATH: ${{ inputs.sarif-data-path }}
    INPUTS_QHELP_ROOT: ${{ inputs.qhelp-root }}
    INPUTS_ISSUE_DATA_PATH: ${{ inputs.issue-data-path }}
