on: [push]

permissions: read-all

jobs:
  sarif_to_github_issues_job:
    runs-on: ubuntu-latest
    name: Creating GitHub issues from SARIF files
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize the Sarif-Files-to-GitHub-Issues toolkit
        uses: ./init
        id: init
        with:
          toolkit-version: v0.001'
      # Use the output from the `hello` step
      - name: Get Toolkit downloading status
        run: |
          echo "The time was ${{ steps.init.outputs.time }}"
          echo "The file list was ${{ steps.init.outputs.file-list }}"
          echo "The toolkit path was ${{ steps.init.outputs.toolkit-path }}"

      - name: Parse SARIF files
        uses: ./parsesarif
        id: parsesarif
        with:
          sarif-data-path: '${{github.workspace}}/tests/sarif'
          qhelp-root: 'http://www.sci.brooklyn.cuny.edu/~chen/uploads/research/qhelp'
          issue-data-path: '_s2ghi_/issue_data'
